config/routes.rb
Lire::Application.routes.draw do
  
  get "home/index"
  get "home/about"
  get "home/help"
  get "home/feeds"
  
  post "users/process_login"
  
  get "feeds/cache_needs_update"
  get "feeds/front_page"
  get "feeds/modify"
   
  match 'register' => 'users#new'
  match 'login' => 'users#login'
  match 'logout' => 'users#logout'
  
  match 'process_login' => 'users#process_login'
  match 'readlater/:id', :to => 'readlater#destroy', :as => :readlateritem
  
  root :to => "Home#index"
  
  resources :feeds
  resources :readlater
  resources :users
    
  get ':controller(/:action(/:id))'
  
  
  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :name, :url, :user_id
  #has_many :readlater
  
  before_save do |record|
    unless self.unique then
      raise "Feed name or url already exists."
    end
    
    unless self.user_feed_quota(record.user_id) then
      raise "You cannot agregate more than 40 feeds."
    end
    
    return true
  end
  
  after_create do |record|
    #UserLog.add_action('add_feed')
    return true
  end
  
  def self.get_user_feeds(user_id, full=true)
    if full then
      return Feed.where("user_id = ?", user_id).order("id ASC")
    else
      return Feed.select("id").where("user_id = ?", user_id).order("id ASC").map {|x| x.id}
    end
  end
  
  def unique
    user_feeds = Feed.where("user_id = ? and (name = ? or url = ?)", self.user_id,  self.name, self.url).count
    if user_feeds > 0
      return false
    end
    return true
  end
  
  def user_feed_quota(user_id)
    user_feeds = Feed.where("user_id = ?", user_id).count
    if user_feeds > 40
      return false
    end
    return true
  end
end

app/controllers/feeds_controller.rb
#require 'rubygems'
#require 'open-uri'
#require 'file_cache'
#require 'simple-rss'
require 'feedzirra'
require 'feedbag'
require 'date'
require 'feeds_handler'

class FeedsController < ApplicationController
  before_filter :request_access, :except => [:front_page,:cache_needs_update,:show]
  
  #caches_page :index
  
  $DEBUG = true
  $update_interval = 360
  
  def index
    Rails.logger.debug "################################" if $DEBUG == true
    Rails.logger.debug "#                              #" if $DEBUG == true
    Rails.logger.debug "################################" if $DEBUG == true
    user_id = session[:user_id] or user_id = 15 # world
    $cache_status_file = "cache/last_update_#{user_id}"
    @feeds = Feed.get_user_feeds(user_id)
    # view index javascript call to feeds/front_page
  end
  
  def front_page
    params[:id] ||= nil
    user_id = session[:user_id] or user_id = 15 # world
    
    Rails.logger.debug "Front Page..." if $DEBUG == true
    #if FeedsHandler.cache_needs_update($cache_status_file, $update_interval) then
    
    unless params[:id].nil?  then
        @mem_feeds = FeedsHandler.update_front_page_cache(params[:id].to_i, user_id)
    else
        Rails.logger.debug "Cache up to date, fetting feeds from DB..." if $DEBUG == true
        @mem_feeds = Item.get_user_items(user_id)
    end
    render :partial => 'front_page'
  end
  
  def cache_needs_update
      user_id = session[:user_id] or user_id = 15 # world
      cache_needs_update = FeedsHandler.cache_needs_update($cache_status_file, $update_interval)
      feeds = ''
      if cache_needs_update then
        Rails.logger.debug "Cache needs update, updating..." if $DEBUG == true
        Item.delete_user_items(user_id)
        result = Feed.get_user_feeds(user_id, false)
        feeds = result.join(",")
      end
      result = "#{cache_needs_update.to_s}|#{feeds}"
      render :text => result
  end
  
  def show
    id = params[:id].to_i
    @feedobj = Feed.find(params[:id])
    @feed = FeedsHandler.fetch_feed(@feedobj, false)
    
    unless session[:id].nil? 
      items = Readlateritem.where(["feed_id = ?", @feedobj.id]).select("title")
      @read_later_items = Array.new
      items.each do |i|
        @read_later_items << i.title
      end
    end
    
    render :partial => 'feed'
  end
  
  def show_feed_ajax
    self.show()
  end
  
  def new
    @feed = Feed.new
    @recommended_feeds = RecommendedFeed.all
  end
  
  def edit
    @feed = Feed.find(params[:id])
  end
  
  def modify
    @feeds = Feed.get_user_feeds(session[:user_id])
  end
  
  def update
    @feed = Feed.find(params[:id])
    @feed.update_attributes(params[:feed])
    flash[:notice] = "Feed Updated."
    redirect_to :action => 'modify'
  end
  
  def create
    name = params[:feed][:name]
    url = params[:feed][:url]
    
    if name.blank? then
      flash[:error] = "You must provide a name."
      redirect_to :action => 'new'
      return
    end
    
    if url.blank? then
      flash[:error] = "You must provide a url. It can be either the RSS link or the URI of the page"
      redirect_to :action => 'new'
      return
    end
        
    url = Feedbag.find(url).first
    if url.nil? then
      flash[:error] = "Feed cannot be aggregated."
      redirect_to :action => 'new'
      return
    end
    
    begin   
      @feed = Feed.new(params[:feed])
      @feed.user_id = session[:user_id]
      @feed.save
      flash[:notice] = "Feed Aggregated."
      redirect_to :action => 'index'
    rescue Exception => e
      flash[:error] = e.message
      redirect_to :action => 'new'
    end
  end
  
  def destroy
    Feed.find(params[:id]).destroy
    flash[:notice] = "Feed Deleted."
    redirect_to :action => 'modify'
  end
  
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feed.html.erb
<div class="feed">
     
    <div id="feed_title">
      <a href="<%= @feed.url %>" target="_blank"><%= @feed.title.html_safe %></a>
    </div>
    
    <div id="feed_description"><%= @feed.description %></div>
  <% i=0 %>
  <% @feed.entries.each do |item| %>
  <%
    if defined? item.content then
       content = item.content
   elsif defined? item.summary
       content = item.summary
   end
   inqueue = false
   %>
    <div class="feed_item" id="feed_item_<%= i %>">
      <div class="feed_item_title"><a href="<%= item.url %>" target="_blank"><%= item.title.html_safe %></a></div>
      <% unless session[:id].nil? %>
	      <div class="feed_item_options"> 
	        <% if @read_later_items.include?(item.title.html_safe)  %>
	            <%= link_to 'In queue', { :controller => :readlater, :action => :index }, :class => "btn" %>
	        <% else %>
	            <%= form_tag('/lire/readlater') do %>
	                <%= hidden_field_tag "readlater[title]", item.title.html_safe %>
	                <%= hidden_field_tag "readlater[url]", item.url %>
	                <%= hidden_field_tag "readlater[feed_id]", @feedobj.id %>
	                <%= hidden_field_tag "readlater[date_published]", item.published %>
	                <%= hidden_field_tag 'feed_item_id', "feed_item_#{i}" %>
	                <%= submit_tag "read later", :class => "btn" %>
	            <% end %>
	        <% end %>
	    </div>
	  <% end %>
       <div class="feed_item_date"><%= item.published if defined? item.published %></div>
      <div class="feed_item_text"><%= item.content.html_safe if defined? item.content.html_safe %></div>
      <% unless defined? item.content.html_safe %>
        <div class="feed_item_text"><%= item.summary.html_safe if defined? item.summary.html_safe %></div>
      <% end %>
    </div>
    <% 
      i +=1;
      if i >= 20 then
        break
      end 
    %>
  <% end %>
</div>

app/views/feeds/_form.html.erb
<h2>Add Feed</h2>
<div class="box">
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@llamada.errors.count, "error") %> prohibited this llamada from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="span span4">
  <div class="field">
    Name:<br />
    <%= f.text_field :name, :size => "50" %>
  </div>
  <div class="field">
    URL:<br />
    <%= f.text_field :url, :size => "50" %>
  </div>
</div>
<br/>
<div class="actions">
  <%= f.submit 'Aggregate', :class => 'btn' %>
</div>

<% end %>
</div>

app/views/feeds/_front_page.html.erb
<div class="feed">
        <% i=0 %>
        <% @mem_feeds.each do |item| %>
          <div class="feed_item" id="feed_item_<%= i %>">
            <div class="feed_item_title_index"><a href="<%= item.url %>" target="_blank"><%= item.title.html_safe %></a></div>
            <div class="feed_item_date"><%= item.published if defined? item.published %></div>
          </div>  
        <% end %>
</div>

app/views/feeds/_load_feeds.html.erb
<script type="text/javascript">
$(document).ready(function()
{ 
	    var origin = window.location.origin;
	    //var path = document.location.pathname;
	    //var path = path.replace(/\//,'');
	    //var env = path.replace(/feeds/,'');
        var env = "";
        var url = origin + "/" + env + "feeds/cache_needs_update";
        
        //alert(window.location.origin);
        //alert(hostname);
        //alert(env)
        //alert(url);
        
        $.get(url, function(cache_needs_update) {
        	needs_update = new String(cache_needs_update);
        	var obj = needs_update.split("|");
        	needs_update = obj[0];
        	feeds = obj[1].split(",");
        	
        	if(needs_update == 'true')
	        {  
		        for(i=0;i < feeds.length; i++)
		        {
		        	var url = origin + "/" + env + "feeds/front_page/" + feeds[i];
		        	$.get(url, function(html) {
			        	$("#random-feeds").append(html);
			    	});
		        }
		    }
		    else
		    {
		    	var url = origin + "/" + env + "feeds/front_page/";
		        $.get(url, function(html) {
			        $("#random-feeds").html(html);
			    });
		    }
	    });
        
        /*
	    $.get(url, function(html) {
	        	$("#random-feeds").html(html);
	    });
        */
        $(".feed-link").each(function () {
          $(this).click(function() {
            var id = this.id;
            var arrid = id.split('-');
            id = arrid[2];
            
            var url = origin + "/" + env + "feeds/"+id;
            $.get(url, function(html) {
	          $("#random-feeds").html(html);
	        }); 
          });
        });
});
//feed_path(feed)
</script>
<div id="feeds-list">
	<h1>Feeds:</h1>
	<% if @feeds.length > 0 then %>
<table>
    <% @feeds.each do |feed| %>
    <tr>
      <td class="feed-list-item"><%= link_to feed.name, '#', :id => "feed-link-#{feed.id}", :class => 'feed-link' %></td>
      <!-- ><td><%= link_to "Edit", edit_feed_path(feed), :class => 'btn'  %></td>
      <td><%= link_to 'Delete', feed, :confirm => 'Sure?...He no le muevas si no eres Hector... aun no le pongo seguridad a esto', :method => :delete, :class => 'btn' %></td>-->
    </tr>
    <% end %>
</table>
    <% else %>
    You don't have any feeds... <%= link_to 'Add Feed', new_feed_path, :class=> "btn" %>
	<% end %>
</div>
<div id='random-feeds'>
</div>
<br/><br/>

app/views/feeds/_nav_links.html.erb
<div class="pull-right">
   <%= link_to 'Return to Feeds', feeds_path, :class => "btn" %>
<%= link_to 'Read Later Queue', { :controller => :readlater, :action => :index }, :class => "btn" %>
</div>

app/views/feeds/edit.html.erb
<h2>Edit feed URL</h2>
<%= render 'form' %>

app/views/feeds/index.html.erb
<%= render 'load_feeds' %>

app/views/feeds/modify.html.erb
<div id="feeds-list">
	<h1>Modify Feeds</h1>
<table>
    <% @feeds.each do |feed| %>
    <tr>
      <td class="feed-list-item"><%= link_to feed.name, '#', :id => "feed-link-#{feed.id}", :class => 'feed-link' %></td>
      <td><%= link_to "Edit", edit_feed_path(feed), :class => 'btn'  %></td>
      <td><%= link_to 'Delete', feed, :confirm => 'sure you want to dele this?', :method => :delete, :class => 'btn' %></td>
    </tr>
    <% end %>
</table>
</div>

app/views/feeds/new.html.erb
<%= render 'form' %>


<h3>Recommended Feeds</h3>
<table>
<% @recommended_feeds.each do |recommended_feed| %>
    <tr>
      <td>
      	<%= form_for(@feed) do |f| %>
          <%= f.hidden_field :name, :value => recommended_feed.name %>
          <%= f.hidden_field :url, :value => recommended_feed.url %>
          <%= f.submit 'Add' %>
        <% end %>
     </td><td><%= recommended_feed.name %></td><td><%= recommended_feed.about %></td>
    </tr>
<% end %>
</table>

app/views/feeds/show.html.erb
<%= render 'nav_links' %>
<div class="feed">
     
    <div id="feed_title">
      <a href="<%= @feed.url %>" target="_blank"><%= @feed.title.html_safe %></a>
    </div>
    
    <div id="feed_description"><%= @feed.description %></div>
  <% i=0 %>
  <% @feed.entries.each do |item| %>
  <%
    if defined? item.content then
       content = item.content
   elsif defined? item.summary
       content = item.summary
   end
   inqueue = false
   %>
    <div class="feed_item" id="feed_item_<%= i %>">
      <div class="feed_item_title"><a href="<%= item.url %>" target="_blank"><%= item.title.html_safe %></a></div>
      <% unless session[:id].nil? %>
	      <div class="feed_item_options"> 
	        <% if @read_later_items.include?(item.title.html_safe)  %>
	            <%= link_to 'In queue', { :controller => :readlater, :action => :index }, :class => "btn" %>
	        <% else %>
	            <%= form_tag('/lire/readlater') do %>
	                <%= hidden_field_tag "readlater[title]", item.title.html_safe %>
	                <%= hidden_field_tag "readlater[url]", item.url %>
	                <%= hidden_field_tag "readlater[feed_id]", @feedobj.id %>
	                <%= hidden_field_tag "readlater[date_published]", item.published %>
	                <%= hidden_field_tag 'feed_item_id', "feed_item_#{i}" %>
	                <%= submit_tag "read later", :class => "btn" %>
	            <% end %>
	        <% end %>
	    </div>
      <% end %>
       <div class="feed_item_date"><%= item.published if defined? item.published %></div>
      <div class="feed_item_text"><%= item.content.html_safe if defined? item.content.html_safe %></div>
      <% unless defined? item.content.html_safe %>
        <div class="feed_item_text"><%= item.summary.html_safe if defined? item.summary.html_safe %></div>
      <% end %>
    </div>
    <% 
      i +=1;
      if i >= 20 then
        break
      end 
    %>
  <% end %>
</div>